name: AWS Lambda CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: List Files (Debugging Step)
        run: |
          echo "Listing current directory contents:"
          ls -al

      - name: Run Unit Tests
        run: |
          pytest tests/quantum_tests.py

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAXNGUVEGFXVWD2XY3
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Confirm Function.zip is Present
        run: |
          echo "Verifying function.zip is present..."
          ls -al function.zip

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name cloud-quantum-integration \
            --zip-file fileb://function.zip

      - name: Verify Lambda Deployment
        run: |
          echo "Deployment complete. Checking Lambda function..."
          aws lambda get-function --function-name cloud-quantum-integration


