name: Deploy Quantum Model

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t briontechnology/quantum-model:${{ github.sha }} .
        docker push briontechnology/quantum-model:${{ github.sha }}

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name QuantumModelDeployment \
          --image-uri briontechnology/quantum-model:${{ github.sha }}
